### ISSUE TITLE
Compiled library location

### ISSUE THREAD

**Issue by taylormcd** [byuflowlab/Snopt.jl#3]
The Snopt.jl file as is requires some changes in where the Snopt shared library is located.  My current setup is just to place the library in usr/local/lib and change all references to it to "libsnopt".  This works ok, but I would prefer to work on a clean git branch if at all possible.  Assuming the compiled library is located in a fixed location relative to Snopt.jl this shouldn't be hard to implement using the macro @\_\_FILE\_\_.  Is there a reason the current implementation is set up the way it is?

**Comment by andrewning** [comment]
It already assumes a fixed location (where it is already): snopt/libsnopt.  I don't need to move mine anywhere, but maybe the current directory is not on the path in Linux.  We should look at how other Julia packages with external binaries handle this.

**Comment by taylormcd** [comment]
It must be platform specific issue then.  The BinDeps package provides one example of library linking (and building), but might be overkill for this package.

**Comment by andrewning** [comment]
I fixed this issue as well as a few others.  
- fixed library location issue
- made this an actual package
- added a build.jl file so you can just Pkg.build("Snopt") (checks for Linux or Mac to get the right extension --- no support for windows)
- moved the examples to actual unit tests
