### ISSUE TITLE
Large integer return as 'xopt' - SNOPT-7.2.11

### ISSUE THREAD

**Issue by ca0h** [byuflowlab/Snopt.jl#4]
I am getting a vector of large integers as the solution of my problem. 

`xopt, fopt, info = snopt(prob, x0, xl, xu, options)`
`println(xopt[1])`
 
The result is
`4647443604925490822`
The number in 'snopt-print.out' is correct.

It works fine for the test problems.

**Comment by andrewning** [comment]
hmm.  Do you have a minimal working example?  We wouldn't be able to investigate without more information.

**Comment by ca0h** [comment]
Please see below. Thanks.
```
# workspace()
using Snopt

xl = [1;    1;       0;     1;    0;  85;  90;  3; 1.2; 145;  3;    85]
xu = [2000; 16000; 120; 5000; 2000; 93; 95; 12; 4.0; 162; 24000; 465000]
x0 = [1700; 16000; 100; 3000; 2000; 90; 94; 10;   2;  150; 18000; 200000]

function prob(x)
    # --- objective ---
    f = 5.04*x[1] + 0.035*x[2] + 10*x[3] + 3.36*x[5] - 0.063*x[4]*x[7]

    # --- gradient of obj ---
    dfdx = zeros(12)
    dfdx[1] = 5.04
    dfdx[2] = 0.035
    dfdx[3] = 10
    dfdx[4] = -0.063*x[7]
    dfdx[5] = 3.36
    dfdx[7] = -0.063*x[4]

    c = []
    dcdx = []

    fail = false

    return f, c, dfdx, dcdx, fail
end

options = Dict{String, Any}()
options["Derivative option"] = 1
options["Verify level"] = 1

xopt, fopt, info = snopt(prob, x0, xl, xu, options)
println(xopt)
println(info)
```

**Comment by andrewning** [comment]
The problem is x0.  As you've defined it, it is an integer array.  If you just change one of the values to a float (say 1700.0) then everything works.  I didn't dig into exactly what the problem is, but my guess is that it is in passing data between fortran and julia and it's looking for a certain length field which is not what it expects (integer vs float).

**Comment by ca0h** [comment]
That works perfectly. Thanks a lot for you help!
